name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust to match your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.*  # Adjust to your Node.js version

      - name: Install project dependencies
        run: |
          npm install

      - name: Build the JavaScript project
        run: npm run build  # Adjust to your build command
      
      - name: Deploy the build
        run: |
          git config --global user.email "udosenakane@gmail.com"
          git config --global user.name "Akan Udosen"

          cd ./dist
          git init
          git checkout -b main

          git remote add production https://github.com/udosenakane/udosenakane.github.io.git
          git add .
          git commit -m "Deploy via GitHub Actions"
          git push --force production main